services:
  - type: web
    name: cilawebsite-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: Backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: NODE_ENV
        value: production
